server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: signature-service

spring:
  application:
    name: electronic-signature-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  thymeleaf:
    cache: false

logging:
  level:
    com.signature: DEBUG
    org.springframework.security: DEBUG

signature:
  storage:
    path: ./documents
  certificate:
    path: certificates/
    private-key: signing-key.pem
    certificate: certificate.pem
