server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: signature-service

# SSL Profile - Use with: mvn spring-boot:run -Dspring-boot.run.profiles=ssl
# Or: java -jar app.jar --spring.profiles.active=ssl
